
const listings = [
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(1).jpg?alt=media&token=17f78ca8-3bfd-4900-bba5-48113c4d61fb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(2).png?alt=media&token=3cc3e259-b5e5-4b97-8cbd-0e82f31e5c58',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(3).jpg?alt=media&token=578d7d75-a620-459a-89c4-3c5da1ee7daf'
        ],
        imageNames: [],
        name: "Newly renovated property",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "3767 Wisteria Ln SW, Atlanta, GA 30331",
        regularPrice: 260000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(1).webp?alt=media&token=0ec41664-c3e4-41ba-a142-3d1bcb774c28',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(2).webp?alt=media&token=0e886ce4-bb63-4f9f-8197-9219a16625ff',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(3).webp?alt=media&token=cc4f136f-cde3-4b9e-9e0c-3f83ba46d82d',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(4).webp?alt=media&token=8cc1b22b-dbfb-492c-ad7d-0ff0cbae7f36',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(5).webp?alt=media&token=ff8c4de0-52e8-4171-8215-0c91bdc9d12c',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(6).webp?alt=media&token=8a356527-9962-433b-846e-59d92031c1d2'],
        imageNames: [],
        name: "Ranch House",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "1134 Winding Dr, Cherry Hill, NJ 08003",
        regularPrice: 15000000,
        discountPrice: 0,
        bedrooms: 4,
        bathrooms: 5,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(1).webp?alt=media&token=f59057f9-b2e2-47f1-ac43-996adfadc57a', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(2).webp?alt=media&token=0416566e-9fad-497d-8a1e-f77b3f85da67',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(3).webp?alt=media&token=855f5794-222d-4ca9-9f56-ccce16a8990a'],
        imageNames: [],
        name: "The Grand Cherry Hill Apartment Homes",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "1900 and 1920 Frontage Rd, Cherry Hill, NJ 08034",
        regularPrice: 1354,
        discountPrice: 200,
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        parking: true,
        type: "rent",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(1).webp?alt=media&token=4e10899c-ca6d-40e4-937c-1a45ac8508ef', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(2).webp?alt=media&token=630467d1-6451-499b-a143-708f877963d8',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(3).webp?alt=media&token=8916d26f-e809-4d6e-8997-7eca466c59eb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(4).webp?alt=media&token=9a8608e6-cbe7-471f-8d7b-cebafa4618b2'],
        imageNames: [],
        name: "Single family property",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 3900,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: false,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(1).webp?alt=media&token=f862c852-fc80-4cc4-969d-0bbd7a870e9d', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(2).webp?alt=media&token=0a3f3263-6f65-4769-81b1-d9282f0b3ae6',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(3).webp?alt=media&token=f5084489-9424-4955-a3a3-f81358172ee5',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(4).webp?alt=media&token=749f60d1-9cfc-4f1f-aeea-1f4795c41c4b'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Welcome Home. 3 Bed 2.5 Bath Townhome on the East Side of Cherry Hill. Walk in the front door into the foyer that overlooks a spacious living room with wood fireplace. Off the living room is a small dining room and large family room with vaulted ceilings. Kitchen is white cabinets with upgraded granite countertops. 1 car garage and powder room off the kitchen. Off the Family room and dining rooms are access to the outside patio. Up the stairs to the second floor is the hallway to 3 bedrooms, a hall bathroom and the primary bedroom has big closet and on suite full bathroom. Bathrooms need updating and home needs floors and paint. SOLD AS IS. Buyer responsible for the Certificate of Occupancy and all inspections.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 2800000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: true,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(1).webp?alt=media&token=5febf3a7-0e46-4afa-941b-620b14248889', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(2).webp?alt=media&token=5f6ca9ef-3a15-42fd-bdcb-c939aff67f62',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(3).webp?alt=media&token=2c8433b7-0b46-4ad8-97a1-c456e5df2c9e',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(4).webp?alt=media&token=f7d9bbf0-fe75-458f-ab48-beb3fddbf3bf',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(5).webp?alt=media&token=d0bbb375-9289-4f03-8e7f-5416510cc5a0'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Discover the allure of this completely redone first-floor condo in The Woods II in Cherry Hill! Enter into a spacious living room featuring a cozy fireplace and a separate dining area with newer flooring throughout. The updated kitchen boasts gorgeous countertops, white cabinetry, and stainless steel appliances. The primary bedroom offers a luxurious escape with a soaking tub and a separate stall shower, complemented by double closets. The second bedroom, also with double closets, provides comfortable accommodation. A full guest bathroom adds convenience. Outside, relax on the private patio. Don't miss the opportunity to see this exceptional home schedule your private tour TODAY!",
        address: "1915 The Woods Ii, Cherry Hill, NJ 08003",
        regularPrice: 250000,
        discountPrice: 15000,
        bedrooms: 2,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    }, {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(1).jpg?alt=media&token=17f78ca8-3bfd-4900-bba5-48113c4d61fb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(2).png?alt=media&token=3cc3e259-b5e5-4b97-8cbd-0e82f31e5c58',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(3).jpg?alt=media&token=578d7d75-a620-459a-89c4-3c5da1ee7daf'
        ],
        imageNames: [],
        name: "Newly renovated property",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "3767 Wisteria Ln SW, Atlanta, GA 30331",
        regularPrice: 260000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(1).webp?alt=media&token=0ec41664-c3e4-41ba-a142-3d1bcb774c28',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(2).webp?alt=media&token=0e886ce4-bb63-4f9f-8197-9219a16625ff',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(3).webp?alt=media&token=cc4f136f-cde3-4b9e-9e0c-3f83ba46d82d',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(4).webp?alt=media&token=8cc1b22b-dbfb-492c-ad7d-0ff0cbae7f36',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(5).webp?alt=media&token=ff8c4de0-52e8-4171-8215-0c91bdc9d12c',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(6).webp?alt=media&token=8a356527-9962-433b-846e-59d92031c1d2'],
        imageNames: [],
        name: "Ranch House",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "1134 Winding Dr, Cherry Hill, NJ 08003",
        regularPrice: 15000000,
        discountPrice: 0,
        bedrooms: 4,
        bathrooms: 5,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(1).webp?alt=media&token=f59057f9-b2e2-47f1-ac43-996adfadc57a', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(2).webp?alt=media&token=0416566e-9fad-497d-8a1e-f77b3f85da67',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(3).webp?alt=media&token=855f5794-222d-4ca9-9f56-ccce16a8990a'],
        imageNames: [],
        name: "The Grand Cherry Hill Apartment Homes",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "1900 and 1920 Frontage Rd, Cherry Hill, NJ 08034",
        regularPrice: 1354,
        discountPrice: 200,
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        parking: true,
        type: "rent",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(1).webp?alt=media&token=4e10899c-ca6d-40e4-937c-1a45ac8508ef', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(2).webp?alt=media&token=630467d1-6451-499b-a143-708f877963d8',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(3).webp?alt=media&token=8916d26f-e809-4d6e-8997-7eca466c59eb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(4).webp?alt=media&token=9a8608e6-cbe7-471f-8d7b-cebafa4618b2'],
        imageNames: [],
        name: "Single family property",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 3900,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: false,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(1).webp?alt=media&token=f862c852-fc80-4cc4-969d-0bbd7a870e9d', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(2).webp?alt=media&token=0a3f3263-6f65-4769-81b1-d9282f0b3ae6',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(3).webp?alt=media&token=f5084489-9424-4955-a3a3-f81358172ee5',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(4).webp?alt=media&token=749f60d1-9cfc-4f1f-aeea-1f4795c41c4b'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Welcome Home. 3 Bed 2.5 Bath Townhome on the East Side of Cherry Hill. Walk in the front door into the foyer that overlooks a spacious living room with wood fireplace. Off the living room is a small dining room and large family room with vaulted ceilings. Kitchen is white cabinets with upgraded granite countertops. 1 car garage and powder room off the kitchen. Off the Family room and dining rooms are access to the outside patio. Up the stairs to the second floor is the hallway to 3 bedrooms, a hall bathroom and the primary bedroom has big closet and on suite full bathroom. Bathrooms need updating and home needs floors and paint. SOLD AS IS. Buyer responsible for the Certificate of Occupancy and all inspections.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 2800000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: true,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(1).webp?alt=media&token=5febf3a7-0e46-4afa-941b-620b14248889', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(2).webp?alt=media&token=5f6ca9ef-3a15-42fd-bdcb-c939aff67f62',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(3).webp?alt=media&token=2c8433b7-0b46-4ad8-97a1-c456e5df2c9e',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(4).webp?alt=media&token=f7d9bbf0-fe75-458f-ab48-beb3fddbf3bf',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(5).webp?alt=media&token=d0bbb375-9289-4f03-8e7f-5416510cc5a0'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Discover the allure of this completely redone first-floor condo in The Woods II in Cherry Hill! Enter into a spacious living room featuring a cozy fireplace and a separate dining area with newer flooring throughout. The updated kitchen boasts gorgeous countertops, white cabinetry, and stainless steel appliances. The primary bedroom offers a luxurious escape with a soaking tub and a separate stall shower, complemented by double closets. The second bedroom, also with double closets, provides comfortable accommodation. A full guest bathroom adds convenience. Outside, relax on the private patio. Don't miss the opportunity to see this exceptional home schedule your private tour TODAY!",
        address: "1915 The Woods Ii, Cherry Hill, NJ 08003",
        regularPrice: 250000,
        discountPrice: 15000,
        bedrooms: 2,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(1).jpg?alt=media&token=17f78ca8-3bfd-4900-bba5-48113c4d61fb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(2).png?alt=media&token=3cc3e259-b5e5-4b97-8cbd-0e82f31e5c58',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost1(3).jpg?alt=media&token=578d7d75-a620-459a-89c4-3c5da1ee7daf'
        ],
        imageNames: [],
        name: "Newly renovated property",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "3767 Wisteria Ln SW, Atlanta, GA 30331",
        regularPrice: 260000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(1).webp?alt=media&token=0ec41664-c3e4-41ba-a142-3d1bcb774c28',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(2).webp?alt=media&token=0e886ce4-bb63-4f9f-8197-9219a16625ff',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(3).webp?alt=media&token=cc4f136f-cde3-4b9e-9e0c-3f83ba46d82d',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(4).webp?alt=media&token=8cc1b22b-dbfb-492c-ad7d-0ff0cbae7f36',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(5).webp?alt=media&token=ff8c4de0-52e8-4171-8215-0c91bdc9d12c',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost2(6).webp?alt=media&token=8a356527-9962-433b-846e-59d92031c1d2'],
        imageNames: [],
        name: "Ranch House",
        description: "Welcome to 1134 Winding Drive, the epitome of luxury and sophistication nestled in the heart of Cherry Hills most prestigious neighborhood of Voken Tract. This magnificent fully renovated home sits on almost 2 lush acres and offers an unparalleled living experience of privacy, style, and convenience. The home's opulence is immediately apparent upon entering. Your eyes will be drawn to 7-1/2 wide European oak wood floors, soft white and beige finishes, and black windows, all of which set a tone of refined elegance that flows throughout. The abundance of natural light and open floor plan accentuates the soft tones, and adds a sense of tranquility and spaciousness.",
        address: "1134 Winding Dr, Cherry Hill, NJ 08003",
        regularPrice: 15000000,
        discountPrice: 0,
        bedrooms: 4,
        bathrooms: 5,
        furnished: true,
        parking: true,
        type: "sale",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(1).webp?alt=media&token=f59057f9-b2e2-47f1-ac43-996adfadc57a', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(2).webp?alt=media&token=0416566e-9fad-497d-8a1e-f77b3f85da67',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost3(3).webp?alt=media&token=855f5794-222d-4ca9-9f56-ccce16a8990a'],
        imageNames: [],
        name: "The Grand Cherry Hill Apartment Homes",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "1900 and 1920 Frontage Rd, Cherry Hill, NJ 08034",
        regularPrice: 1354,
        discountPrice: 200,
        bedrooms: 1,
        bathrooms: 1,
        furnished: false,
        parking: true,
        type: "rent",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(1).webp?alt=media&token=4e10899c-ca6d-40e4-937c-1a45ac8508ef', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(2).webp?alt=media&token=630467d1-6451-499b-a143-708f877963d8',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(3).webp?alt=media&token=8916d26f-e809-4d6e-8997-7eca466c59eb',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost4(4).webp?alt=media&token=9a8608e6-cbe7-471f-8d7b-cebafa4618b2'],
        imageNames: [],
        name: "Single family property",
        description: "We are taking comfort to a higher standard. Welcome to The Grand, luxury high-rise apartments in Cherry Hill, NJ. From our concierge service to our well-appointed apartment homes, you will sense The Grand was designed with your personal comfort in mind. Experience a lifestyle defined by lavish amenities including a clubhouse, an infinity pool, gyms, a wellness studio, movie theatre and business center.The Grand Cherry Hill offers a vast array of bright, airy apartment homes carefully detailed with granite countertops, GE Energy Saver appliances, carpeting and expansive closets. Enjoy private balconies that offer a scenic sanctuary for relaxing outdoors or nestle inside the well-appointed comfort of your five-star Cherry Hill apartment home.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 3900,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: false,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(1).webp?alt=media&token=f862c852-fc80-4cc4-969d-0bbd7a870e9d', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(2).webp?alt=media&token=0a3f3263-6f65-4769-81b1-d9282f0b3ae6',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(3).webp?alt=media&token=f5084489-9424-4955-a3a3-f81358172ee5',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost5(4).webp?alt=media&token=749f60d1-9cfc-4f1f-aeea-1f4795c41c4b'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Welcome Home. 3 Bed 2.5 Bath Townhome on the East Side of Cherry Hill. Walk in the front door into the foyer that overlooks a spacious living room with wood fireplace. Off the living room is a small dining room and large family room with vaulted ceilings. Kitchen is white cabinets with upgraded granite countertops. 1 car garage and powder room off the kitchen. Off the Family room and dining rooms are access to the outside patio. Up the stairs to the second floor is the hallway to 3 bedrooms, a hall bathroom and the primary bedroom has big closet and on suite full bathroom. Bathrooms need updating and home needs floors and paint. SOLD AS IS. Buyer responsible for the Certificate of Occupancy and all inspections.",
        address: "335 Hinchman Ave, Cherry Hill, NJ 08002",
        regularPrice: 2800000,
        discountPrice: 0,
        bedrooms: 3,
        bathrooms: 3,
        furnished: true,
        parking: false,
        type: "rent",
        offer: false,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(1).webp?alt=media&token=5febf3a7-0e46-4afa-941b-620b14248889', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(2).webp?alt=media&token=5f6ca9ef-3a15-42fd-bdcb-c939aff67f62',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(3).webp?alt=media&token=2c8433b7-0b46-4ad8-97a1-c456e5df2c9e',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(4).webp?alt=media&token=f7d9bbf0-fe75-458f-ab48-beb3fddbf3bf',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost6(5).webp?alt=media&token=d0bbb375-9289-4f03-8e7f-5416510cc5a0'],
        imageNames: [],
        name: "Robert Bunis with Prime Realty Partners",
        description: "Discover the allure of this completely redone first-floor condo in The Woods II in Cherry Hill! Enter into a spacious living room featuring a cozy fireplace and a separate dining area with newer flooring throughout. The updated kitchen boasts gorgeous countertops, white cabinetry, and stainless steel appliances. The primary bedroom offers a luxurious escape with a soaking tub and a separate stall shower, complemented by double closets. The second bedroom, also with double closets, provides comfortable accommodation. A full guest bathroom adds convenience. Outside, relax on the private patio. Don't miss the opportunity to see this exceptional home schedule your private tour TODAY!",
        address: "1915 The Woods Ii, Cherry Hill, NJ 08003",
        regularPrice: 250000,
        discountPrice: 15000,
        bedrooms: 2,
        bathrooms: 2,
        furnished: true,
        parking: true,
        type: "sale",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },
    {
        imageUrls: ['https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost7(1).webp?alt=media&token=efd636c2-c00c-4867-be37-bda0ff98c88b', 'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost7(2).webp?alt=media&token=ad95ef81-4306-419f-98e5-9bbba680e701',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost7(3).webp?alt=media&token=d3024ce4-a537-48e7-8b8b-c05c2b83bc02',
            'https://firebasestorage.googleapis.com/v0/b/mern-real-estate-9a14b.appspot.com/o/SeedsImages%2Fpost7(4).webp?alt=media&token=e0b25c45-b3d7-4e24-a662-b172f6ec11ad'],
        imageNames: [],
        name: "Newly renovated single family home",
        description: "Immaculate SINGLE FAMILY home for rent in desirable Erlton section of Cherry Hill. This masterfully cared for 3-4 Bedroom 1.5 Bath Cape Cod home was totally renovated top to bottom in 2015!! HVAC, refinished natural hardwood flooring, COMPLETELY REMODELED EAT IN KITCHEN with GRANITE COUNTERTOPS are just a few of the upgrades that make this home TURN-KEY. Upon entry from the 4 car driveway you will notice the lovely hardwood floors in the living room opening up to a first-class kitchen with a large Island, Granite Countertops, newer appliances, tile floors and plenty of cabinet space for the modern family ready to host! NEED AN IN-LAW SUITE WITH A MAIN FLOOR FULL BATH?",
        address: "116 New Hampshire Ave, Cherry Hill, NJ 08002",
        regularPrice: 3000,
        discountPrice: 280,
        bedrooms: 4,
        bathrooms: 2,
        furnished: false,
        parking: true,
        type: "rent",
        offer: true,
        userRef: '656fafb13c9b08467774033f'
    },


]


export default listings